### ISSUE TITLE
Setstatuson is not working on my Sony X85C

### ISSUE THREAD

**Issue by kskaret** [rwifall/homebridge-sonybraviatv#1]
I think the script sends a JSON as follows: 
{ method: 'setPowerStatus',
    params: [{status: 1}],
    id: 1,
    version: '1.0'
}

But the TV expects the parameter to be a boolean, like this: 
{ method: 'setPowerStatus',
    params: [{status: true}],
    id: 1,
    version: '1.0'
}

**Comment by rwifall** [comment]
What OS are you running home bridge on?

**Comment by rwifall** [comment]
I couldn't reproduce this on OS X El Capitan and Homebridge 0.2.11
But I put in some code to force the status to be a boolean, so hopefully it was coming in as an int before and this fixes the issue.  If it doesn't fix it for you, please re-open the issue and include the log output from home bridge when you try to turn on or off the TV.

**Comment by kskaret** [comment]
Thx! I run it on Raspberry Pi

**Comment by kskaret** [comment]
And the update worked fine!

**Comment by rwifall** [comment]
Great!
