### ISSUE TITLE
Turns off but not on

### ISSUE THREAD

**Issue by sandyjmacdonald** [rwifall/homebridge-sonybraviatv#12]
I have this weird issue where everything seems to be set up correctly and I can turn the TV off, but not on. It's a Sony Bravia KD43XD8077 and I'm running node.js v7.9.0 on a Raspberry Pi Zero W.

**Comment by rwifall** [comment]
Are you seeing any errors in the logs?
What settings are you using?
Are you able to turn on your TV with any other apps?
Are you using the macaddress field in the settings (for TVs that require wake on LAN)?  Have you tried it both with and without that field?
Are you able to turn on your TV with a wake on LAN app on your PC?
Are your Raspberry Pi and TV on the same subnet?

**Comment by mhsurfer** [comment]
I have a similar problem with my KDL-55W756C. With its MAC address in the config, it never turns on. Without the MAC address, it only turns on when turning it off the last time is not that long ago. I assume some deeper sleep state it enters into?! 

I activated Wake on LAN for the TV in the router (FritzBox) and did all the settings you're mentioning  but it does not seem to work. At least, the TV does not show an image using WOL. I don't know whether it might awake from this deeper sleep state to a "normal" one. When giving a MAC address, do you only send the WOL or do you combine a WOL and a regular HTTP wake up call? I assume the former but maybe my TV would need the latter?!

**Comment by ghost** [comment]
Hi everyone,
I know this thread is kind of old, but I had experienced this same issue a few months ago. What I did was simply remove the MAC address from the config file, but I left the polling and interval there. I have an XBR-65X850D. It works perfectly, except there is slight lag when using the TV to trigger other accessories. For example, I have Pioneer VSX receiver, and I have HomeKit setup to turn it on when the TV turns, and without the MAC address, it is not as quick to trigger the automation. Hope this helps!
