### ISSUE TITLE
For Sony Bravia Linux

### ISSUE THREAD

**Issue by luvmex** [rwifall/homebridge-sonybraviatv#15]
My TV is Sony Bravia but the system based on Linux, Is is plugin capable to connect with it?
I have tried the most homebridge for sony plugin but those fail to connect.
 
Thanks.

**Comment by rwifall** [comment]
As stated in the [readme](https://github.com/rwifall/homebridge-sonybraviatv/blob/master/README.md), this supports Sony Bravia TVs running Android TV.
