### ISSUE TITLE
Warnings when installing/updating

### ISSUE THREAD

**Issue by lswee** [rwifall/homebridge-sonybraviatv#16]
Hey,

I've been looking at using cron to automate updating my plugins.

There are two warning messages for homebridge-sonybraviatv:
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer

Are these things that the plugin pulls or do I need to update them myself (how would I go about doing this)?

Should I worry about these warnings?

Thanks

**Comment by rwifall** [comment]
I don't use home bridge or this plugin anymore, so can't easily update and test this.
I'd happily take a pull request to fix these issues.

**Comment by rwifall** [comment]
The dependencies and versions are in package.json.
request and/or wake_on_lan would need to specify newer versions and then test to make sure that it didn't break the code.
