### ISSUE TITLE
TV Doesn't turn on/off

### ISSUE THREAD

**Issue by sansin** [rwifall/homebridge-sonybraviatv#4]
I see TV is added to my accessories but when I turn on or off, I see below error message.

[9/28/2016, 8:58:46 PM] [Sony TV] Error 'null' setting lock state. Response: {"auth_url":{"default":"http://192.168.1.xxx/sony/webauth/auth_default"}}

**Comment by rwifall** [comment]
Did you setup the presharedkey in your config?
And what is your TV model?

**Comment by rwifall** [comment]
Verified that this error is what you get if you haven't setup the presharedkey settings.   Updated the install instructions in commit 9ef5e1a1ff7eb4c574f918694a1d590fa17302b8 to make this more clear.
1. Change "Authentication" to "Normal and Pre-Shared Key" in your Android Settings->Network->IP Control->Authentication
2. Enter a "Pre-Shared Key" in your Android TV Settings->Network->IP control->Pre-Shared Key
   Put that same string in the presharedkey field in the configuration file

If that doesn't fix your problem, please reopen this bug.
