### ISSUE TITLE
How can new functionality be added to this plugin?

### ISSUE THREAD

**Issue by rwifall** [rwifall/homebridge-sonybraviatv#5]
From @russelh76

> > I suspect I'm missing something, but I'm a noob and see nowhere else to ask questions regarding the project. I think I can easily modify your index.js such that a function exists for all of the major functionality (mute, channelUp, blah, blah, blah). The part that I'm missing is how is this exposed to homebridge/homekit? I've missed a step (or 3) somewhere. My HTML mockup is here: https://dl.dropboxusercontent.com/u/11118349/SonyTV/TV.html

**Comment by rwifall** [comment]
The part of the code that hooks this up to home bridge/homekit is this:

```
     this.service = new Service.Switch(this.name);

     this.service
        .getCharacteristic(Characteristic.On)
        .on('get', this.getOn.bind(this))
        .on('set', this.setOn.bind(this));
```

So Apple HomeKit natively supports certain types of services.  For instance a "Switch".  And these services have certain standard Characteristics, like "Characteristic.On" for the Switch.

You can also add custom/optional characteristics, but those may not be supported in different user interfaces.

Here are the characteristics that are supported by HomeBridge:
[HomeKitTypes.js](https://github.com/KhaosT/HAP-NodeJS/blob/7fb8c2924e8bb08a548bf101d0605db09a6f6952/lib/gen/HomeKitTypes.js)

**Comment by russellh76** [comment]
Thank you again for taking the time.  I see in that same project a little documentation.  It's clear that TV control is in some sense limited by homekit.  A quick glance didn't turn up anything that would stand-in for channel or input.  Though I did see mute/volumeup/volumedown.  I'll do a little reading and see if I can't ask a tougher question next time.
