### ISSUE TITLE
Support volume control

### ISSUE THREAD

**Issue by dylanslewis** [rwifall/homebridge-sonybraviatv#6]
While this plugin appears to be the best for Sony TVs, there are other homebridge Sony TV plugins that allow volume control (I'm not using them because the basic functionality doesn't work as well as this plugin).

Would it be possible to add volume as a characteristic? 

Thanks

**Comment by rwifall** [comment]
I don't have plans to do this anytime soon, but would be open to accepting a pull request with those changes.

**Comment by langovoi** [comment]
@dylanslewis try use my plugin, it must work with most Smart TV: https://github.com/langovoi/homebridge-upnp#readme

I will glad to see model number if plugin will work with your TV.
