### ISSUE TITLE
Poll TV status

### ISSUE THREAD

**Issue by dylanslewis** [rwifall/homebridge-sonybraviatv#7]
When homebridge is started, the state of the TV is not known. The state is only shown after it has been requested by a HomeKit app. This means that the log stating `Getting whether Sony TV is on...` is only shown after 'forcing' an update of the state.

Would it be possible to poll the TV every few seconds for its state, rather than waiting for the phone to request it? This would allow more stable stable triggers in HomeKit, e.g. turn on a certain scene when the TV turns on.

**Comment by ghost** [comment]
I just implemented this: https://github.com/rwifall/homebridge-sonybraviatv/pull/9

**Comment by rwifall** [comment]
Fixed by commit #0B404F4

**Comment by rwifall** [comment]
Fixed by commit https://github.com/rwifall/homebridge-sonybraviatv/commit/0b404f4617703ab3e45bb497dd9860e012ca8483
