### ISSUE TITLE
Turn ON doesn't work

### ISSUE THREAD

**Issue by m3lvn** [rwifall/homebridge-sonybraviatv#8]
Hi,

I have been searching for ages to get my new Sony TV to work with Homebridge. With your code I am able to turn off the TV but I am not able to turn it back on. I am 100% convinced that I am able to turn it on remotely as the Sony app "Video & TV SideView" works as a charm (both turning on & off the TV).

Any idea what I should do?

**Comment by rwifall** [comment]
The most common problem would be for it to be a configuration or networking issue.
Without more information I have no idea what the issue could be.

For configuration, have you set it up like suggested in the read me?  In particular:

> If your TV requires Wake-on-Lan to power-on, enter your TV MAC address in the macaddress field.

For networking, is the TV on the same subnet as your home bridge server?

Are there any errors being reported in the home bridge log when you try to turn on the TV?

If you report your configuration, what you see in the home bridge log I might be able to make some other suggestions.

**Comment by eaglexp** [comment]
I have the same issue, when the TV is turned on manually, I can use your code to turn it off, in homebridge log: 
[3/18/2017, 10:02:08 PM] [Sony TV] Getting whether Sony TV is on...
[3/18/2017, 10:02:08 PM] [Sony TV] TV status is active
[3/18/2017, 10:02:19 PM] [Sony TV] Set value to false

While when the TV is in OFF status, and I click the homekit button, in homebridge log:  
[3/18/2017, 10:03:19 PM] [Sony TV] Set value to true
but nothing happens, the homekit button icon shows ON status, no error reported.

Please advise how to solve this issue.

config.json (part of):
"accessory": "SonyBraviaTV",
"name": "Sony TV",
"macaddress": "04:5D:4B:01:20:23",
"ipaddress": "192.168.0.93",
"presharedkey": "123456"

**Comment by ghost** [comment]
@m3lvn, @eaglexp can you turn on your TV using wake-on-lan?
Using `wakeonlan '04:5D:4B:01:20:23'` in Linux for example?

**Comment by rwifall** [comment]
@eaglexp Some Sony TVs need macaddress for WOL, but some do not.  Did you try without the macaddress as well?

**Comment by rwifall** [comment]
Since there have been no responses to enable tracking the issues and I have not been able to reproduce this I will assume it was configuration issue.
